[package]
name = "dijkstra_maze"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.23"
rand = "0.8"
egui = "0.23"
image = "0.24"
winapi = { version = "0.3", features = ["winuser", "windef"] }